### ISSUE TITLE
Hal Core 3.0 missing db constraints

### ISSUE THREAD

**Issue by nagibyro** [hal-platform/hal#48]
### Description
Some values defined as unique in the doctrine yaml files are not created with the unique constraint by the phinx migrations.

### Acceptance Criteria
All fields that have unique constraint defined in `orm.yml` should be generated with constraints in phinx migrations

### Notes
The following constraints are missing
- **Users**
    - [username](https://git/hal/hal-core/blob/3.x/configuration/doctrine/User.orm.yml#L19) 
- **Organization**
    - [identifier](https://git/hal/hal-core/blob/3.x/configuration/doctrine/Organization.orm.yml#L18) 
- **Environment**
    - [name](https://git/hal/hal-core/blob/3.x/configuration/doctrine/Environment.orm.yml#L19)
- **Application**
    - [identifier](https://git/hal/hal-core/blob/3.x/configuration/doctrine/Application.orm.yml#L19)

There are some things that are not set as unique that maybe should be -- `Users email`, `Organization names`, `AWS key`?

**Comment by nagibyro** [comment]
### More Notes
Also the migrations for the Application table does not created the embedded columns from [github application](https://github.com/hal-platform/hal-core/blob/master/configuration/doctrine/Application.GitHubApplication.orm.yml)

### Test Case
```php
#!/usr/bin/env php
<?php

namespace QL\Hal\Bin;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Hal\Core\Entity\Application;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

$root = realpath(__DIR__ . '/..');

if (!$container = @include $root . '/vendor/autoload.php') {
    echo "Boom goes the dynamite.\n";
    exit(1);
}

// Set Timezone to UTC
ini_set('date.timezone', 'UTC');
date_default_timezone_set('UTC');
error_reporting(E_ALL | E_STRICT);

$di = new ContainerBuilder;
$builder = new YamlFileLoader($di, new FileLocator($root));
$builder->load('configuration/hal-core.yml');

$di->compile();

/** @var EntityManagerInterface $em */
$em = $di->get('doctrine.em');


$org = new Organization(null, 'sample-org', 'sample-org-name');
$app = new Application(null, 'bnagi', 'sample-app');
$app->withOrganization($org);
$em->persist($org);
$em->persist($app);
$em->flush();
```

### Error
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gitHub_github_owner' in 'field list' in /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#3 /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php(366): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1014): Doctr in /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gitHub_github_owner' in 'field list' in /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO applications (id, identifier, name, gitHub_github_owner, gitHub_github_repository, organization_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["3a972a9f27af4e65b190770a039946a7", "bnagi", "sample-app", "", "", null]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'gitHub_github_owner' in 'field list' in /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71

Call Stack:
    0.0019     358440   1. {main}() /Users/bnagi/projects/hal-project/hal-core/bin/tmp.php:0
    0.0581    5356808   2. Doctrine\ORM\EntityManager->flush() /Users/bnagi/projects/hal-project/hal-core/bin/tmp.php:35
    0.0581    5356808   3. Doctrine\ORM\UnitOfWork->commit() /Users/bnagi/projects/hal-project/hal-core/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:356
```

**Comment by nagibyro** [comment]
It'd be nice to use the phinx migrations in the unit tests instead of the orm schema builder to catch these types of issues but sqlite doesn't have a `json` type unless you install an extension.
